//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesDEMO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.ProducInOrder = new HashSet<ProducInOrder>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int PickUpPointId { get; set; }
        public int UserId { get; set; }
        public int Code { get; set; }
        public int StatusId { get; set; }
    
        public virtual PickUpPoint PickUpPoint { get; set; }
        public virtual Status Status { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProducInOrder> ProducInOrder { get; set; }
    }
}
