//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesDEMO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProducInOrder = new HashSet<ProducInOrder>();
        }
    
        public int Id { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public int UnitId { get; set; }
        public decimal Price { get; set; }
        public int ProviderId { get; set; }
        public int ProducerId { get; set; }
        public int CategoryId { get; set; }
        public int Discount { get; set; }
        public int AmountInStock { get; set; }
        public string Discription { get; set; }
        public string Photo { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ProducerId ProducerId1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProducInOrder> ProducInOrder { get; set; }
        public virtual ProviderId ProviderId1 { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
